Create 12.pmw.hwc.csv
john30/ebusd-configuration pull request #177
Opened 2020-04-26 12:12 UTC by mucheinz

time periods for circulation pump - english

2020-06-01 09:13 UTC, john30 commented on ebusd-2.x.x/en/vaillant/12.pmw.hwc.csv
> +# type (r[1-9];w;u),circuit,name,[comment],[QQ],ZZ,PBSB,[ID],field1,part (m/s),datatypes/templates,divider/values,unit,comment,,,
why not simply include timer.inc ?

2020-09-20 10:35 UTC, john30 requested changes

2020-09-20 10:35 UTC, john30 commented on ebusd-2.x.x/en/vaillant/12.pmw.hwc.csv
> +*r,cp,,,,,"B504",,,,,,,,,,
this is no longer needed, right?

2020-09-20 10:35 UTC, john30 commented on ebusd-2.x.x/en/vaillant/12.pmw.hwc.csv
> +*w,cp,,,,,"B505","09",,,,,,,,,
this is no longer needed, right?

2020-09-20 16:13 UTC, mucheinz reviewed
correct - no longer needed

2020-09-20 16:13 UTC, closed without merging