Implement VWZ Live Monitor readings & Test Menu
john30/ebusd-configuration pull request #316
Opened 2023-02-13 16:21 UTC by kjoglum

Following up on PR #160 to implement values from VWZ (heat pump controller).

2023-02-23 22:46 UTC, kjoglum commented
Made some adjustments, and additions for VWZ test menu, believe the PR is ready for evaluation/merge.

2023-03-01 23:41 UTC, Geg0r commented
Tried your PR and I can tell that I receive some additional and valid values for my setup, thx

2023-05-09 19:57 UTC, wimleers commented
Does one need to do something to _trigger_ the live monitor? I've applied this PR and see new fields appear, but none of them appear to be updating?


Examples from `http://mist.local:8080/data`:
```
…
   "YieldTotal": {
    "name": "YieldTotal",
    "passive": false,
    "write": false,
    "lastup": 0
   },
…
   "Hc1FlowTemp": {
    "name": "Hc1FlowTemp",
    "passive": false,
    "write": false,
    "lastup": 0
   },
   "Hc1HeatCurve": {
    "name": "Hc1HeatCurve",
    "passive": false,
    "write": false,
    "lastup": 0
   },
   "Hc1HeatCurveAdaption": {
    "name": "Hc1HeatCurveAdaption",
    "passive": false,
    "write": false,
    "lastup": 0
   },
   "Hc1MaxFlowTempDesired": {
    "name": "Hc1MaxFlowTempDesired",
    "passive": false,
    "write": false,
    "lastup": 0
   },
   "Hc1MinFlowTempDesired": {
    "name": "Hc1MinFlowTempDesired",
    "passive": false,
    "write": false,
    "lastup": 0
   },
…
```

Since there's no heating/cooling demand nor domestic hot water demand, I suspect many values are _expected_ to not update. But the _yield_ should be updated?

2023-05-09 20:15 UTC, kjoglum commented
@wimleers
Regarding yield, you should ask the question outside this PR, as this PR is not related. For additional data covered by this PR, one is required to send a corresponding write message to retrieve value.

2023-05-09 20:41 UTC, wimleers commented
Thanks for the incredibly fast response!

> For additional data covered by this PR, one is required to send a corresponding write message to retrieve value.

So this PR does not decode any additional messages already being transmitted on the bus?

Your comment at https://github.com/john30/ebusd-configuration/pull/160#issuecomment-590116529 suggests I should do
```
ebusctl read -v LiveMonitor
```

Is that right?

The tricky thing is that I'm running `ebusd` in Docker and hence don't have easy access to `ebusctl` 😬 I just tried compiling it and it failed on macOS 🤷

2023-05-09 20:58 UTC, wimleers commented
I got a great hint from somebody in a Dutch forum (you know who you are!): to use `http://mist.local:8080/data/hmu?maxage=60` instead.

That worked!

Output:
```
{
 "hmu": {
  "messages": {   "CompressorExitTemp": {
    "name": "CompressorExitTemp",
    "passive": false,
    "write": false,
    "lastup": 1683665710,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "CompressorIntakeTemp": {
    "name": "CompressorIntakeTemp",
    "passive": false,
    "write": false,
    "lastup": 1683665710,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "CompressorSpeed": {
    "name": "CompressorSpeed",
    "passive": false,
    "write": false,
    "lastup": 1683665710,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "CondensateTemp": {
    "name": "CondensateTemp",
    "passive": false,
    "write": false,
    "lastup": 1683665710,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "ConsumptionThisYear10": {
    "name": "ConsumptionThisYear10",
    "passive": false,
    "write": false,
    "lastup": 1683665711,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "ConsumptionThisYear11": {
    "name": "ConsumptionThisYear11",
    "passive": false,
    "write": false,
    "lastup": 1683665711,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "ConsumptionThisYear12": {
    "name": "ConsumptionThisYear12",
    "passive": false,
    "write": false,
    "lastup": 1683665711,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "ConsumptionThisYear1": {
    "name": "ConsumptionThisYear1",
    "passive": false,
    "write": false,
    "lastup": 1683665711,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "ConsumptionThisYear2": {
    "name": "ConsumptionThisYear2",
    "passive": false,
    "write": false,
    "lastup": 1683665711,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "ConsumptionThisYear3": {
    "name": "ConsumptionThisYear3",
    "passive": false,
    "write": false,
    "lastup": 1683665711,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "ConsumptionThisYear4": {
    "name": "ConsumptionThisYear4",
    "passive": false,
    "write": false,
    "lastup": 1683665712,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "ConsumptionThisYear5": {
    "name": "ConsumptionThisYear5",
    "passive": false,
    "write": false,
    "lastup": 1683665712,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "ConsumptionThisYear6": {
    "name": "ConsumptionThisYear6",
    "passive": false,
    "write": false,
    "lastup": 1683665712,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "ConsumptionThisYear7": {
    "name": "ConsumptionThisYear7",
    "passive": false,
    "write": false,
    "lastup": 1683665712,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "ConsumptionThisYear8": {
    "name": "ConsumptionThisYear8",
    "passive": false,
    "write": false,
    "lastup": 1683665713,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "ConsumptionThisYear9": {
    "name": "ConsumptionThisYear9",
    "passive": false,
    "write": false,
    "lastup": 1683665713,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "ConsumptionTotal": {
    "name": "ConsumptionTotal",
    "passive": false,
    "write": false,
    "lastup": 1683665713,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "CurrentCompressorUtil": {
    "name": "CurrentCompressorUtil",
    "passive": false,
    "write": false,
    "lastup": 1683665713,
    "zz": 8,
    "fields": {
     "0": {"name": "", "value": -1}
    }
   },
   "CurrentConsumedPower": {
    "name": "CurrentConsumedPower",
    "passive": false,
    "write": false,
    "lastup": 1683665713,
    "zz": 8,
    "fields": {
     "0": {"name": "", "value": -0.1}
    }
   },
   "currenterror": {
    "name": "currenterror",
    "passive": false,
    "write": false,
    "lastup": 1683665714,
    "zz": 8,
    "fields": {
     "0": {"name": "error", "value": null},
     "1": {"name": "error", "value": null},
     "2": {"name": "error", "value": null},
     "3": {"name": "error", "value": null},
     "4": {"name": "error", "value": null}
    }
   },
   "CurrentYieldPower": {
    "name": "CurrentYieldPower",
    "passive": false,
    "write": false,
    "lastup": 1683665714,
    "zz": 8,
    "fields": {
     "0": {"name": "", "value": -0.1}
    }
   },
   "DateTime": {
    "name": "DateTime",
    "passive": false,
    "write": false,
    "lastup": 1683665714,
    "zz": 8,
    "fields": {
     "dcfstate": {"value": "nosignal"},
     "btime": {"value": "-:-:-"},
     "bdate": {"value": "-.-.-"},
     "temp2": {"value": null}
    }
   },
   "DeliveryFlow": {
    "name": "DeliveryFlow",
    "passive": false,
    "write": false,
    "lastup": 1683665714,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "EEVPosition": {
    "name": "EEVPosition",
    "passive": false,
    "write": false,
    "lastup": 1683665714,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "EEVTemp": {
    "name": "EEVTemp",
    "passive": false,
    "write": false,
    "lastup": 1683665714,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "EnergyCool": {
    "name": "EnergyCool",
    "passive": false,
    "write": false,
    "lastup": 1683665715,
    "zz": 8,
    "fields": {
     "energy": {"value": 2303}
    }
   },
   "EnergyHc": {
    "name": "EnergyHc",
    "passive": false,
    "write": false,
    "lastup": 1683665715,
    "zz": 8,
    "fields": {
     "energy": {"value": 2303}
    }
   },
   "EvapTemp": {
    "name": "EvapTemp",
    "passive": false,
    "write": false,
    "lastup": 1683665715,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "FlowTempIn": {
    "name": "FlowTempIn",
    "passive": false,
    "write": false,
    "lastup": 1683665715,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "FlowTempOut": {
    "name": "FlowTempOut",
    "passive": false,
    "write": false,
    "lastup": 1683665715,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "HighPressure": {
    "name": "HighPressure",
    "passive": false,
    "write": false,
    "lastup": 1683665715,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "Hours": {
    "name": "Hours",
    "passive": false,
    "write": false,
    "lastup": 1683665716,
    "zz": 8,
    "fields": {
     "energy": {"value": 2303}
    }
   },
   "HoursCool": {
    "name": "HoursCool",
    "passive": false,
    "write": false,
    "lastup": 1683665716,
    "zz": 8,
    "fields": {
     "energy": {"value": 2303}
    }
   },
   "HoursHc": {
    "name": "HoursHc",
    "passive": false,
    "write": false,
    "lastup": 1683665716,
    "zz": 8,
    "fields": {
     "energy": {"value": 2303}
    }
   },
   "LiveMonitorAirIntake": {
    "name": "LiveMonitorAirIntake",
    "passive": false,
    "write": false,
    "lastup": 1683665717,
    "zz": 8,
    "fields": {
     "temperature": {"value": 12.94}
    }
   },
   "LiveMonitorCompressorModulation": {
    "name": "LiveMonitorCompressorModulation",
    "passive": false,
    "write": false,
    "lastup": 1683665717,
    "zz": 8,
    "fields": {
     "percentage": {"value": 0}
    }
   },
   "LiveMonitorCurrentSupply": {
    "name": "LiveMonitorCurrentSupply",
    "passive": false,
    "write": false,
    "lastup": 1683665718,
    "zz": 8,
    "fields": {
     "temperature": {"value": 36.75}
    }
   },
   "LiveMonitorDesiredSupply": {
    "name": "LiveMonitorDesiredSupply",
    "passive": false,
    "write": false,
    "lastup": 1683665718,
    "zz": 8,
    "fields": {
     "temperature": {"value": 20.00}
    }
   },
   "LiveMonitorMain": {
    "name": "LiveMonitorMain",
    "passive": false,
    "write": false,
    "lastup": 1683665718,
    "zz": 8,
    "decodeerror": "ERR: invalid position"
   },
   "LiveMonitorPowerConsumption": {
  [...]

2023-05-09 21:12 UTC, kjoglum commented
@wimleers 
You are mixing your issue into a PR for totally different data values. I.e. you have issues with `yield` which already is implemented in the master branch. This PR covers different Live Monitor values desired added to the main branch. So you should create a separate `Issue`, not mixing issue comments in a unrelated PR. This PR relates to line 7-13, 25-26 and 30-51.

2023-05-11 11:31 UTC, wimleers commented
_Sorry — I didn't mean to mix things up. I just saw a bunch of "yield"-mentioning lines changed in your PR. So I jumped to that one first. Apologies for the distraction._

Let me try to get this back on track 😊 

I'm especially interested in 7–13 and 30–51. So that's `ReadFlowTempOut`, `FlowTempOut`, `ReadFlowTempIn`, `FlowTempIn`, …, `CompressorSpeed` Looking at the output I shared above for those values, you see:

## ✅ 7–13

| Key | Value |
|--------|--------|
| `LiveMonitorDesiredSupply` | `20.0` |
| `LiveMonitorCurrentSupply` | `36.75` | 
| `LiveMonitorPowerConsumption` | `0.0` |
| `LiveMonitorPowerGenerated` | `0.0` |
| `LiveMonitorCompressorModulation` | `0` |
| `LiveMonitorAirIntake` | `12.94` |

Clearly these work fine! 🥳

## ❌ 30–51

| Key | Value |
|--------|--------|
| `EEVPosition` | `ERR: invalid position` |
| `FlowTempOut` | `ERR: invalid position` |
| `FlowTempIn` | `ERR: invalid position` |
| `DeliveryFlow` | `ERR: invalid position` |
| `CompressorExitTemp` | `ERR: invalid position` |
| `CompressorIntakeTemp` | `ERR: invalid position` | 
| `EEVTemp` | `ERR: invalid position` |
| `HighPressure` | `ERR: invalid position` |
| `CondensateTemp` | `ERR: invalid position` |
| `EvapTemp` | `ERR: invalid position` |
| `CompressorSpeed` | `ERR: invalid position` |

What can I be doing wrong to get `ERR: invalid position`?

I'm using the latest version of `ebusd`, version `23.1`: https://github.com/john30/ebusd/releases/tag/23.1

That string originates from https://github.com/john30/ebusd/blob/23.1/src/lib/ebus/result.cpp#L39. `grep`ping the codebase reveals:
- `StringDataType::readSymbols()` returns it when the provided offset would put it beyond the length of the given input: https://github.com/john30/ebusd/blob/1895339e4514a3fbb97f46cdd41170ca3f81ad75/src/lib/ebus/datatype.cpp#L146-L155
- `SingleDataField::read()` returns it when the provided offset would put it outside the given data: https://github.com/john30/ebusd/blob/1895339e4514a3fbb97f46cdd41170ca3f81ad75/src/lib/ebus/data.cpp#L512-L522
- Same for [other occurrences](https://github.com/search?q=repo%3Ajohn30/ebusd%20RESULT_ERR_INVALID_POS&type=code).

I see 4 possible explanations — maybe you can think of more:
1. The configuration in the CSV file is incorrect.
2. The CSV file is correct, but it is actually not compatible with my devices: Vaillant aroTHERM 75/5 + uniTOWER split - VWL IS 78/5. They're reported as 
3. I've misconfigured `ebusd`.
4. The `ebusd` adapter is not working correctly.

I personally suspect the root cause is `1. The configuration in the CSV file is incorrect.`, because only `08.hmu.csv` is being updated. But `http://mist.local:8080/data/scan.08` returns:
```
{
  "scan.08": {
    "messages": {
      "": {
        "name": "",
        "passive": false,
        "write": false,
        "lastup": 1683803790,
        "zz": 8,
        "fields": {
          "MF": {
            "value": "Vaillant"
          },
          "ID": {
            "value": "HMU00"
          },
          "SW": {
            "value": "0522"
          },
          "HW": {
            "value": "5103"
          }
        }
      },
      "id": {
        "name": "id",
        "passive": false,
        "write": false,
        "lastup": 0
      }
    }
  },
  "global": {
…
  }
}
```

**… no mention of "VWZ" ☝️ … but I do see a mention of "VWZ" under http://mist.local:8080/data/scan.76:**

```
{
  "scan.76": {
    "messages": {
      "": {
        "name": "",
        "passive": false,
        "write": false,
        "lastup": 1683663282,
        "zz": 118,
        "fields": {
          "MF": {
            "value": "Vaillant"
          },
          "ID": {
            "value": "VWZ00"
          },
          "SW": {
            "value": "0522"
          },
          "HW": {
            "value": "5103"
          }
        }
      },
      "id": {
        "name": "id",
        "passive": false,
        "write": false,
        "lastup": 1683763260,
        "zz": 118,
        "fields": {
          "prefix": {
            "value": "21"
          },
          "year": {
            "value": "22"
          },
          "week": {
            "value": "33"
          },
          "product": {
            "value": "0010022070"
          },
          "supplier": {
            "value": "3100"
          },
          "counter": {
            "value": "006482"
          },
          "suffix": {
            "value": "N8"
          }
        }
      }
    }
  },
  "global": {
…
  }
}
```

Any chance we need a new `76.*.csv` file for me and perhaps some other file for you, for lines 30–51?

How to know which one it is? I'm _very_ eager to help you land this! 😊

2023-05-11 16:56 UTC, wimleers commented
Doesn't that mean that lines 30–51 should be moved _out of_ `08.hmu.csv` and into a more specific `.csv` file?

2023-05-11 17:54 UTC, kjoglum commented
08 is the only device reporting these values om the bus. And in fact, 08 already contains some uniTower values which give the same error (invalid position) for VWZ AI. So I believe these need to co-exist in 08.

2023-05-13 10:12 UTC, wimleers commented
> 08 already contains some uniTower values which give the same error (invalid position) for VWZ AI.

To me that suggests that those values are also misplaced.

I wish I understood enough already about the architecture to make an informed suggestion where that should be placed 😅

2023-05-13 11:57 UTC, kjoglum commented
I am neither familiar with the architecture behind, just been able to decode messages on the bus. The issue must be that VWZ AI and uniTower both are types of HMU, using 08 as slave address, even though they appear to have different functionality/data. Possible also related to values of interest being replicas of actual button presses on the HMU’s, whereas VWZ AI and uniTower have different menu setup.

On the other hand, I do not see why this should be an issue? Why can we not have a 08 csv file covering both, even though some values would be unavailable across VWZ AI/uniTower..?

2023-05-16 09:19 UTC, wimleers commented
>  I do not see why this should be an issue? Why can we not have a 08 csv file covering both, even though some values would be unavailable across VWZ AI/uniTower..?

"unavailable" would be fine, but `ERR: invalid position` is an _error_ — don't you think that's a problem?

2023-05-16 09:48 UTC, wimleers commented
See my in-progress review at https://github.com/john30/ebusd-configuration/pull/330#issuecomment-1549324679 — that PR works far better for my system.

@kjoglum Could you please test _that_ PR so we can start the work to _merge_ these two PRs?

2023-05-17 13:19 UTC, kjoglum commented
@wimleers 
Uncertain how the combination PR would maintain interests for the VWZ AI / aroTherm combination. Write messages are required to mimic menu button press before getting read values, which I do not see in the combination PR.

2024-01-14 17:04 UTC, john30 requested changes
merge with upstream is missing

2024-01-21 22:20 UTC, Dzanar commented
I have a Vaillant VWL75/5AS heat pump with VWZ AI. When I used this configuration file to read parameters while heating domestic hot water, the pump behaved strangely. It turns off every now and then, and then restarts in hot water heating mode. I am using MQTT to read parameters.

2024-02-06 20:40 UTC, kjoglum commented
Merge conflicts resolved.

This PR is also a combination file based on input in PR #330.

2024-02-11 16:44 UTC, merged

2024-02-13 02:32 UTC, pulquero commented on ebusd-2.1.x/de/vaillant/08.hmu.csv
> -r,,EnergyIntegral,,,,,21,,,integral,,°min,aktuelles Energieintegral in °min,,,,,,,,,,,,,,,,,,
Energy integral got lost in the merge.

2024-02-13 06:55 UTC, copacetic82 commented
@john30 as of 11.02.2024 about 12:45 my ebusd is missing the following:
hmu CurrentConsumedPower
hmu CurrentYieldPower

The "LiveMonitorPowerConsumption" and "LiveMonitorPowerGenerated" values seem to be incorrect i.e. consumption is very low (sometimes 0,1KW) and generated is alwas 0.

Any information on this? 

`11.02.2024 12:45

root@server3:/home/serveradmin# docker exec ebusd ebusd -V
ebusd 23.3.23.3
root@server3:/home/serveradmin# docker exec ebusd ebusctl info
version: ebusd 23.3.23.3
update check: OK, device firmware 1[8419] available
device: 172.20.24.25:9999, TCP, enhanced, firmware 1.1[7f16].2[73c8]
signal: acquired
symbol rate: 63
max symbol rate: 193
min arbitration micros: 1
max arbitration micros: 495
min symbol latency: 6
max symbol latency: 11
scan: finished
reconnects: 0
masters: 6
messages: 744
conditional: 15
poll: 266
update: 10
address 00: master #1
address 03: master #11
address 05: slave #1, scanned "MF=Vaillant;ID=VR921;SW=2801;HW=5703"
address 08: slave #11, scanned "MF=Vaillant;ID=HMU00;SW=0607;HW=5103", loaded "vaillant/08.hmu.csv"
address 0a: slave, scanned "MF=Vaillant;ID=PMW01;SW=0206;HW=8302", loaded "vaillant/0a.pmw.hwc.csv"
address 10: master #2
address 15: slave #2, scanned "MF=Vaillant;ID=70000;SW=0614;HW=6903", loaded "vaillant/15.700.csv"
address 26: slave, scanned "MF=Vaillant;ID=VR_71;SW=0104;HW=0503", loaded "vaillant/26.vr_71.csv"
address 31: master #8, ebusd
address 36: slave #8, ebusd
address 71: master #9
address 76: slave #9, scanned "MF=Vaillant;ID=VWZIO;SW=0607;HW=5103"
address f7: master #20
address fc: slave #20, scanned "MF=Vaillant;ID=PMW01;SW=0206;HW=8302"

root@server3:/



ebusd/hmu/CurrentConsumedPower
{
  "0": {
    "name": "",
    "value": 1.7,
    "unit": "kW",
    "comment": "aktueller Stromverbrauch der Wärmepumpe in kW"
  }
}

ebusd/hmu/CurrentYieldPower

{
  "0": {
    "name": "",
    "value": 7.1,
    "unit": "kW",
    "comment": "aktuell gewonnene Energie aus der Umwelt in kW"
  }
}


root@server3:/home/serveradmin# docker exec ebusd ebusctl find -v
700 AdaptHeatCurve = yesno=no
700 BankHolidayEndPeriod = no data stored
700 BankHolidayStartPeriod = no data stored
700 ccTimer.Friday = from=06:00;to=22:00;from=-:-;to=-:-;from=-:-;to=-:-
700 ccTimer.Monday = from=06:00;to=22:00;from=-:-;to=-:-;from=-:-;to=-:-
700 ccTimer.Saturday = from=07:30;to=23:30;from=-:-;to=-:-;from=-:-;to=-:-
700 ccTimer.Sunday = from=07:30;to=22:00;from=-:-;to=-:-;from=-:-;to=-:-
700 ccTimer.Thursday = from=06:00;to=22:00;from=-:-;to=-:-;from=-:-;to=-:-
700 ccTimer.Tuesday = from=06:00;to=22:00;from=-:-;to=-:-;from=-:-;to=-:-
700 ccTimer.Wednesday = from=06:00;to=22:00;from=-:-;to=-:-;from=-:-;to=-:-
700 ContinuosHeating = no data stored
700 currenterror = error=-;error=-;error=-;error=-;error=-
700 CylinderChargeHyst = no data stored
700 CylinderChargeOffset = no data stored
700 Date = date=13.02.2024
700 DisplayedOutsideTemp = tempv=4.41016
700 errorhistory = no data stored
700 FrostOverRideTime = no data stored
700 GlobalSystemOff = yesno=no
700 Hc1ActualFlowTempDesired = tempv=40.2687
700 Hc1AutoOffMode = offmode=night
700 Hc1CircuitType = mctype=mixer
700 Hc1ExcessTemp = calibrationv=3
700 Hc1FlowTemp = tempv=39.75
700 Hc1HeatCurve = =0.9
700 Hc1HeatCurveAdaption = =0.0
700 Hc1MaxFlowTempDesired = tempv=60
700 Hc1MinFlowTempDesired = tempv=24
700 Hc1MixerMovement = no data stored
700 Hc1PumpStatus = =1
700 Hc1RoomTempSwitchOn = rcmode=off
700 Hc1Status = =1
700 Hc1SummerTempLimit = tempv=20
700 Hc2ActualFlowTempDesired = tempv=0.0
700 Hc2AutoOffMode = offmode=eco
700 Hc2CircuitType = mctype=inactive
700 Hc2ExcessTemp = calibrationv=0.0
700 Hc2FlowTemp = tempv=-
700 Hc2HeatCurve = =0.6
700 Hc2HeatCurveAdaption = =0.0
700 Hc2MaxFlowTempDesired = tempv=55
700 Hc2MinFlowTempDesired = tempv=15
700 Hc2MixerMovement = no data stored
700 Hc2PumpStatus = =0
700 Hc2RoomTempSwitchOn = rcmode=off
700 Hc2Status = =0
700 Hc2SummerTempLimit = tempv=21
700 Hc3ActualFlowTempDesired = tempv=0.0
700 Hc3AutoOffMode = offmode=eco
700 Hc3CircuitType = mctype=inactive
700 Hc3ExcessTemp = calibrationv=0.0
700 Hc3FlowTemp = tempv=-
700 Hc3HeatCurve = =0.6
700 Hc3HeatCurveAdaption = =0.0
700 Hc3MaxFlowTempDesired = tempv=55
700 Hc3MinFlowTempDesired = tempv=15
700 Hc3MixerMovement = no data stored
700 Hc3PumpStatus = =0
700 Hc3RoomTempSwitchOn = rcmode=off
700 Hc3Status = =0
700 Hc3SummerTempLimit = tempv=21
700 HcStorageTempBottom = tempv=-
700 HcStorageTempTop = tempv=-
700 HolidayEndPeriod = hto=01.01.2015
700 HolidayStartPeriod = hfrom=01.01.2015
700 HolidayTemp = tempv=5
700 HwcBankHolidayEndPeriod = no data stored
700 HwcBankHolidayStartPeriod = no data stored
700 HwcFlowTemp = tempv=0.0
700 HwcHolidayEndPeriod = no data stored
700 HwcHolidayStartPeriod = no data stored
700 HwcLockTime = no data stored
700 HwcMaxFlowTempDesired = tempv=80
700 HwcOpMode = opmode=auto
700 HwcParallelLoading = no data stored
700 HwcSFMode = sfmode=auto
700 HwcStorageTemp = tempv=46
700 HwcStorageTempBottom = tempv=-
700 HwcStorageTempTop = tempv=-
700 HwcTempDesired = tempv=50
700 hwcTimer.Friday = from=05:30;to=22:00;from=00:00;to=00:00;from=00:00;to=00:00
700 hwcTimer.Monday = from=05:30;to=22:00;from=00:00;to=00:00;from=00:00;to=00:00
700 hwcTimer.Saturday = from=07:00;to=23:30;from=00:00;to=00:00;from=00:00;to=00:00
700 hwcTimer.Sunday = from=07:00;to=22:00;from=00:00;to=00:00;from=00:00;to=00:00
700 hwcTimer.Thursday = from=05:30;to=22:00;from=00:00;to=00:00;from=00:00;to=00:00
700 hwcTimer.Tuesday = from=05:30;to=22:00;from=00:00;to=00:00;from=00:00;to=00:00
700 hwcTimer.Wednesday = from=05:30;to=22:00;from=00:00;to=00:00;from=00:00;to=00:00
700 HydraulicScheme = no data stored
700 Installer1 = no data stored
700 Installer2 = no data stored
700 KeyCodeforConfigMenu = no data stored
700 MaintenanceDate = no data stored
700 MaintenanceDue = no data stored
700 ManualCooling = =0
700 MaxCylinderChargeTime = no data stored
700 MaxRoomHumidity = =40
700 MultiRelaySetting = no data stored
700 noiseReductionTimer.Friday = from=06:00;to=22:00;from=-:-;to=-:-;from=-:-;to=-:-
700 noiseReductionTimer.Monday = from=06:00;to=22:00;from=-:-;to=-:-;from=-:-;to=-:-
700 noiseReductionTimer.Saturday = from=07:30;to=23:30;from=-:-;to=-:-;from=-:-;to=-:-
700 noiseReductionTimer.Sunday = from=07:30;to=22:00;from=-:-;to=-:-;from=-:-;to=-:-
700 noiseReductionTimer.Thursday = from=06:00;to=22:00;from=-:-;to=-:-;from=-:-;to=-:-
700 noiseReductionTimer.Tuesday = from=06:00;to=22:00;from=-:-;to=-:-;from=-:-;to=-:-
700 noiseReductionTimer.Wednesday = from=06:00;to=22:00;from=-:-;to=-:-;from=-:-;to=-:-
700 OpMode = opmode=auto
700 OpModeCooling = opmode=auto
700 OpModeEffect = zonesel=alle
700 OpModeVentilation = opmode=auto
700 OutsideTempAvg = tempv=7.56641
700 PhoneNumber1 = no data stored
700 PhoneNumber2 = no data stored
700 PrEnergySum = energy4=14181
700 PrEnergySumHc = energy4=10919
700 PrEnergySumHcLastMonth = energy4=1026
700 PrEnergySumHcThisMonth = energy4=174
700 PrEnergySumHwc = energy4=3262
700 PrEnergySumHwcLastMonth = energy4=132
700 PrEnergySumHwcThisMonth = energy4=58
700 PrFuelSum = no data stored
700 PrFuelSumHc = no data stored
700 PrFuelSumHcLastMonth = no data stored
700 PrFuelSumHcThisMonth = no data stored
700 PrFuelSumHwc = no data stored
700 PrFuelSumHwcLastMonth = no data stored
700 PrFuelSumHwcThisMonth = no data stored
700 PumpAdditionalTime = no data stored
700 SFMode = sfmode=auto
700 SolarYieldTotal = energy4=0
700 SystemFlowTemp = tempv=45.125
700 tariffTimer.Friday = from=11:00;to=13:00;from=-:-;to=-:-;from=-:-;to=-:-
700 tariffTimer.Monday = from=11:00;to=13:00;from=-:-;to=-:-;from=-:-;to=-:-
700 tariffTimer.Saturday = from=11:00;to=13:00;from=-:-;to=-:-;from=-:-;to=-:-
700 tariffTimer.Sunday = from=11:00;to=13:00;from=-:-;to=-:-;from=-:-;to=-:-
700 tariffTimer.Thursday = from=11:00;to=13:00;from=-:-;to=-:-;from=-:-;to=-:-
700 tariffTimer.Tuesday = from=11:00;to=13:00;from=-:-;to=-:-;from=-:-;to=-:-
700 tariffTimer.Wednesday = from=11 [...]

2024-02-13 10:44 UTC, kjoglum commented
@copacetic82 
Strange, as basically nothing is changed besides changing naming convention from `CurrentConsumedPower` to `LiveMonitorPowerConsumption` and from `CurrentYieldPower` to `LiveMonitorPowerGenerated`. Values retrieved should be similar to values read from your heat pump controller menu.

Could you try the following sequence, and show response?
`ebusctl write -c hmu ReadLiveMonitor FF3224`
`ebusctl read -v LiveMonitorPowerConsumption`
`ebusctl f -h LiveMonitorPowerConsumption`

And similarly:
`ebusctl write -c hmu ReadLiveMonitor FF3223`
`ebusctl read -v LiveMonitorPowerGenerated`
`ebusctl f -h LiveMonitorPowerGenerated`

2024-02-13 14:28 UTC, kjoglum commented
@copacetic82 
`CurrentConsumedPower` and `CurrentYieldPower` would regardless be historical values after the merge (not updated), provided you are using central config files.

However, `LiveMonitorPowerConsumption` would be equal to `CurrentConsumedPower`, identified under same PBSB/ID, i.e. b51a..05..ff3224. And following HEX decode for `0aff083501000000000000`, having IGN3, would convert to 0.1 kW. 

Same as `LiveMonitorPowerGenerated` would be equal to `CurrentYieldPower`.

What are those values as read from your controller menu?

2024-02-13 19:13 UTC, copacetic82 commented
@kjoglum unfortunately no success yet, and I dont think waiting any longer will change the outcome. It showed me a more or less realistic reading once today (dont know why), and afterwards it only shows a consumption of max 0,1KW.  See the screenshots below for a comparison of a normal day with old and new config file.

Everytime I checked with "ebusd ebusctl find -v" I get a reading between 0.0 and 0.1, so its definitely not a homeassistant or MQTT issue:
hmu LiveMonitorPowerConsumption = energy=0.1
hmu LiveMonitorPowerGenerated = energy=0.0

![old](https://github.com/john30/ebusd-configuration/assets/45660618/1fb2dadc-9a60-4a7b-9a68-c0a82c78678b)
![new](https://github.com/john30/ebusd-configuration/assets/45660618/906e7de1-8a23-4c85-b8a2-38f056803af6)

2024-02-13 20:07 UTC, kjoglum commented
@copacetic82 
Again, strange, as the decode is set up more or less identical for new/old values.

Do you have a MQTT config for requesting/retrieving `CurrentConsumedPower` values, which then needs to be changed to request/retrieve `LiveMonitorPowerConsumption`?

Pretty sure if you run `ebusctl write -c hmu ReadLiveMonitor FF3224`, or the MQTT equivalent `mosquitto_pub -m 'FF3224' -t 'ebusd/hmu/ReadLiveMonitor/set` at frequent interval (to trigger value request), you should get the same log trend for `LiveMonitorPowerConsumption`

2024-02-14 06:27 UTC, copacetic82 commented
@kjoglum I am using the automatic homeassistant discovery, so homeassistant is using the following MQTT LiveMonitor topics:

```
{
  "unique_id": "ebusd_hmu_LiveMonitorPowerConsumption_energy",
  "name": "LiveMonitorPowerConsumption energy",
  "device": {
    "identifiers": "ebusd_hmu",
    "manufacturer": "ebusd.eu",
    "name": "ebusd hmu",
    "via_device": "ebusd",
    "sw_version": "23.3",
    "suggested_area": "Heating"
  },
  "value_template": "{{value_json[\"energy\"].value}}",
  "state_topic": "ebusd/hmu/LiveMonitorPowerConsumption",
  "unit_of_measurement": "kW",
  "state_class": "measurement",
  "device_class": "power"
}
```


{
  "unique_id": "ebusd_hmu_LiveMonitorPowerGenerated_energy",
  "name": "LiveMonitorPowerGenerated energy",
  "device": {
    "identifiers": "ebusd_hmu",
    "manufacturer": "ebusd.eu",
    "name": "ebusd hmu",
    "via_device": "ebusd",
    "sw_version": "23.3",
    "suggested_area": "Heating"
  },
  "value_template": "{{value_json[\"energy\"].value}}",
  "state_topic": "ebusd/hmu/LiveMonitorPowerGenerated",
  "unit_of_measurement": "kW",
  "state_class": "measurement",
  "device_class": "power"
}



In comparison to Current*Power:

```
{
  "unique_id": "ebusd_hmu_CurrentConsumedPower_0",
  "name": "CurrentConsumedPower ",
  "device": {
    "identifiers": "ebusd_hmu",
    "manufacturer": "ebusd.eu",
    "name": "ebusd hmu",
    "via_device": "ebusd",
    "sw_version": "23.3",
    "suggested_area": "Heating"
  },
  "value_template": "{{value_json[\"0\"].value}}",
  "state_topic": "ebusd/hmu/CurrentConsumedPower",
  "unit_of_measurement": "kW",
  "state_class": "measurement",
  "device_class": "power"
}

{
  "unique_id": "ebusd_hmu_CurrentYieldPower_0",
  "name": "CurrentYieldPower ",
  "device": {
    "identifiers": "ebusd_hmu",
    "manufacturer": "ebusd.eu",
    "name": "ebusd hmu",
    "via_device": "ebusd",
    "sw_version": "23.3",
    "suggested_area": "Heating"
  },
  "value_template": "{{value_json[\"0\"].value}}",
  "state_topic": "ebusd/hmu/CurrentYieldPower",
  "unit_of_measurement": "kW",
  "state_class": "measurement",
  "device_class": "power"
}
```

I did read the LiveMOnitor Values directly from ebusd while the heatpump was actually runnig. So in my opinion ebusd is not getting the correct values, or is not updating the values frequently enough. Strangely enough I got another "spike" shortly after midnight, so the MQTT config seems to be working:

![image](https://github.com/john30/ebusd-configuration/assets/45660618/ecca598b-7f83-42c5-a4a9-346e162af0c0)

I will try the commands you mentioned when I have more time.

2024-02-15 07:16 UTC, copacetic82 commented
@kjoglum Thank you for your help. Executing "ebusctl write -c hmu ReadLiveMonitor FF3224" repeatedly does indeed show realistic values. How is the new implementation intended to work? Do I manually have to trigger a read? Wont be a problem, I could write an automation for this, but dont know if this this is the way it is supposed to work.

![image](https://github.com/john30/ebusd-configuration/assets/45660618/52ce9746-7260-414e-9320-112a34d678fb)

2024-02-15 07:42 UTC, kjoglum commented
@copacetic82 
Good to hear! For me and my setup, I did not receive any automatic updates for `CurrentConsumedPower` without triggering read, so in an openHAB environment, I have openHAB sending frequent MQTT writes corresponding to `mosquitto_pub -m 'FF3224' -t 'ebusd/hmu/ReadLiveMonitor/set`, thus triggering automatic read for `LiveMonitorPowerConsumption`.

2024-02-16 05:31 UTC, copacetic82 commented
@kjoglum In the past I never had to trigger updates of CurrentConsumedPower. However the value always seemed to be a bit off. e.g I could hear the heatpump running outside, but the value was 0. I tested with an automation, triggering a LiveMonirot update every 20-30sec...the readings now seem to be more accurate than ever, thank you! ;)  The only issue I am having now is that the "LiveMonitorPowerGenerated" sometimes has spikes of very high values (600-800KW), which I cant believe are true, and which mess up the whole graph.  The usual values shown are 5-9KW as expected. Do you also observe this?

![image](https://github.com/john30/ebusd-configuration/assets/45660618/60642319-639b-411c-8cc7-e589080428db)

![image](https://github.com/john30/ebusd-configuration/assets/45660618/bea81b58-fc96-4769-b2a1-7a0cf9fbedd3)

2024-02-17 07:59 UTC, kjoglum commented
@copacetic82 
Good to hear that the config works for you as well.

Haven`t been using the `LiveMonitorPowerGenerated` myself, as I might recall having some spike issues as well. Have activated MQTT, and will follow up on the response.

2024-02-17 19:23 UTC, kjoglum commented
@copacetic82 
I have now been triggering `LiveMonitorPowerGenerated` values as well, and although not getting the value spikes you get, I have similar effect in a smaller scale, i.e. 25 kW. Having both `LiveMonitorPowerConsumption` and `LiveMonitorPowerGenerated` in the same graph (different axis), the spikes seem to appear at the same time as the deicing mode of the heat pump. Uncertain why/what causes this effect, but even though unrealistic values, is seems to be the value sent on the bus.

![image](https://github.com/john30/ebusd-configuration/assets/47720690/aedf4e56-f84d-4da0-bd1d-24ba44e29ce1)

2024-02-18 06:40 UTC, copacetic82 commented
@kjoglum Thanks for checking! If you have the same issue it must be a Vaillant thing. I can possibly do something about this in homeassistant by using filters. But consumption is most important for me, so I might just live with this. Thanks again for your help! :)

2024-02-23 00:13 UTC, dfeist commented
@kjoglum Why did this PR remove "EnergyIntegral", accident?

2024-02-23 16:36 UTC, kjoglum commented
@dfeist 
Seems to have been accidentally removed in the process of merging this PR with changes made in PR# 330. Will correct the mistake and create new PR.

2024-02-25 08:48 UTC, MiroBehrik commented
I have a aroTHERM plus VWL 105/6A fw: 9.01 heat pump. When I used this configuration file to read parameters the pump behaved strangely. 
The pump turned off for no reason and turned on again after a while. 
![obrázok](https://github.com/john30/ebusd-configuration/assets/141213799/90d59350-8966-469c-84c4-7b83e6429d42)

2024-02-25 09:26 UTC, MiroBehrik commented
I have a aroTHERM plus VWL 105/6A fw: 9.01 heat pump. When I used this configuration file to read parameters the pump behaved strangely.  The pump turned off for no reason and turned on again after a while. 
![obrázok](https://github.com/john30/ebusd-configuration/assets/141213799/f3cea980-57e7-4e7d-b6a8-ba96baa70408)

2024-02-26 11:11 UTC, kjoglum commented
@MiroBehrik 
You state that heat pump "turns off" - Does the heat pump actually turn off, or are you basing the statement on the values you read from the bus (i.e. potential missing values)? And if actually turning off, could it be due to no heating demands in that period?

Also, are you sending frequent MQTT write requests to retrieve data?

No changes made to the config files which would turn off the pump.

2024-02-27 17:57 UTC, MiroBehrik commented
Yes, the compressor will turn off. The MQTT reading frequency is once every 2 min

new 08.hmu.csv
![obrázok](https://github.com/john30/ebusd-configuration/assets/141213799/6e5f39c2-42c7-4dc4-a55f-ecf29cc1bb90)
odl 08.hmu.csv
![obrázok](https://github.com/john30/ebusd-configuration/assets/141213799/e6d6d373-bff4-4e34-968d-513066e96cf0)

2024-02-27 18:07 UTC, dfeist commented
@MiroBehrik Seen https://github.com/john30/ebusd/issues/1205 ? Looks like same issue.

2024-02-27 20:46 UTC, kjoglum commented
@MiroBehrik @dfeist 
[Comment](https://github.com/john30/ebusd/issues/1205#issuecomment-1966926455) in #1205 seems to be the likely explanation, i.e. the result of this PR introducing additional write parameters (to manually trigger read values), and how hassio config file/integration is set up to interact with parameters. Might seem like hassio config is causing a write message which shuts down compressor.

This is not an issue for openHAB integration, running "manual" MQTT topics to write/trigger read values. Although unfamiliar about how the hassio config/integration works, and why this issue occurs.

2024-02-27 21:02 UTC, ProdanAS commented
I've managed to see what went on in my HP, when the ebus started sending the request for values. The CalculatedFlowTemp, dropped from 60 to 20 for a fraction of a minute, witch caused the HP, to shutdown due to no heating needs, a little while after, the Calculated value returned to 60, and the compressor started, then this kept happening for ever. 

<img width="563" alt="Skærmbillede 2024-02-22 kl  15 16 21" src="https://github.com/john30/ebusd-configuration/assets/116255260/0a361069-eb78-4010-be9c-f9990e4a5da3">
<img width="568" alt="Skærmbillede 2024-02-22 kl  15 16 15" src="https://github.com/john30/ebusd-configuration/assets/116255260/226c6b39-5591-4278-aded-5ac80156a31f">
<img width="481" alt="Skærmbillede 2024-02-22 kl  15 14 32" src="https://github.com/john30/ebusd-configuration/assets/116255260/bc57fdc9-64ea-4ae4-b730-4ce7a4048fbe">
<img width="605" alt="Skærmbillede 2024-02-22 kl  15 14 08" src="https://github.com/john30/ebusd-configuration/assets/116255260/6ab11eba-31b8-4674-b268-97896c92340c">
<img width="539" alt="Skærmbillede 2024-02-22 kl  15 14 03" src="https://github.com/john30/ebusd-configuration/assets/116255260/4dc80ec6-14af-4566-b6ae-9c6fe3c6c08e">
<img width="638" alt="Skærmbillede 2024-02-22 kl  15 13 49" src="https://github.com/john30/ebusd-configuration/assets/116255260/8433bbc2-c102-4228-93d9-bd2186fd736f">

Maybe this will help someone. Let me know if I can be of assistance with testing.

2024-03-01 18:26 UTC, john30 commented
there was quite some mess around this PR and it is now reverted. better extract the changes to a separate file for inclusion for those interested in it @kjoglum

2024-03-04 07:43 UTC, jkunczik commented
An update from john30/ebusd/issues/1205: We found the culprit. All Home Assistant integrations (MQTT and ebusdpy) actively poll read values. Either the HMU or the controller doesn't take kindly if one of the introduced read values in the updated 08.hmu.csv (we still don't know which) is actively polled by another master, which then leads to a full stop of the heat pump. An issue was opened at ebuspy CrazYoshi/ebusdpy#10 (for the core integration) and a pull request was opened john30/ebusd#1213 to prevent MQTT from actively polling.

After these issues have been addressed, I think the configuration could be merged into master, again.

2024-07-18 05:23 UTC, john30 commented
an extension to message definitions is not supposed to break thousands of running integrations, so clearly changing the polling mechanims on either ebusd or another integration (like ebusdpy) is definitely not the right approach.
someone needs to identify which of the definitions is the root cause (e.g. by bisection).
until this is solved, this PR cannot be merged

2024-12-22 21:09 UTC, john30 commented
looking at this again more closely due to merge activities, I'm pretty sure that the new messages categorized as read but actually starting the live monitoring caused the trouble earlier this year.
it is now reworked and merged in fa74d0c4 with those problematic messages put into service or installer level only and the ones activating the live monitor ensured to be write messages. this way one can actively choose by ebusd start params if those are supposed to be included or not.
some things still need to be sorted out, e.g. the duplication of b51a 05b43400 and b51a 05ff3400 which is now done with a "Stat" prefix to the non-ff ones. but I guess the other PRs have this addressed as well, so might be resolved after those are merged.

2024-12-29 16:51 UTC, john30 commented
please check the [next](https://ebus.github.io/next/) generated csvs with ebusd 24.1 (or current source) as described there or by using a local clone of https://github.com/eBUS/ebus.github.io and using the "next" folder in there