Mainly add support for vaillant B521 service command
john30/ebusd-configuration pull request #368
Opened 2023-11-25 22:28 UTC by tobylorenz

2023-11-25 22:28 UTC, tobylorenz commented
This change is regarding issue 1061 in the main repository: https://github.com/john30/ebusd/issues/1061.

2024-01-14 17:23 UTC, john30 requested changes

2024-01-14 17:23 UTC, john30 commented on ebusd-2.1.x/de/vaillant/e0.omu.csv
> +# B509 service commands
english version is missing

2024-12-25 09:41 UTC, closed without merging

2024-12-25 09:41 UTC, john30 commented
reworked+merged in 679f14cf

2024-12-29 17:57 UTC, tobylorenz commented
Yes, I'll monitor it.