Feature/support ctlv2 #2
john30/ebusd-configuration pull request #386
Opened 2024-01-16 08:27 UTC by mklooss

Based on: https://github.com/john30/ebusd-configuration/pull/266

with Line fix

2024-01-20 15:04 UTC, john30 requested changes

2024-01-20 15:04 UTC, john30 commented on ebusd-2.1.x/de/vaillant/15.ctlv2.csv
> +r;w,,ContinuosHeating,Durchgehendes Heizen,,,,0200,,,tempv,,,"-26=off, when the outside temperature falls below this threshold temperature the continuous heating function is started (off <=> function
spelling seems incorrect and is different from the line in the en file. should rather be continuousHeating for both

2024-01-24 09:10 UTC, mklooss commented
already in @janphkre repo

2024-01-24 09:10 UTC, closed without merging

2024-02-19 11:55 UTC, AlfredJodokusQuack commented
Hi guys,
Sorry for replying to this closed thread. I am still new to github...

Does this issue being closed mean that it is not going to be merged? Because I think this fix would help me with a problem. If it is not going to be merged, can somebody please tell me in which folder to put these files manually?

Thank you!

2024-02-19 16:54 UTC, mklooss commented
@AlfredJodokusQuack see https://github.com/john30/ebusd-configuration/pull/266