Added d.14 & d.15 for hw=7401
john30/ebusd-configuration pull request #442
Opened 2024-11-04 11:33 UTC by mskg

Added PumpPowerDesired, and (current) PumpPower to bai for hw=7401. In my case an eco TEC exclusive. 

Is this the right place? I didn't touch CSVs as those can be generated.

2024-11-04 11:35 UTC, mskg commented
- Found this #210 and #309, but both are different devices

2024-12-28 09:19 UTC, john30 requested changes

2024-12-28 09:19 UTC, john30 commented on src/vaillant/bai.308523_inc.tsp
> +  model PrimaryCircuitFlowRate is ReadonlyRegister<uin100>;
are you sure about the divisor 100?
whats the unit?

2025-02-16 07:08 UTC, john30 commented
reworked+merged in [05690d4](https://github.com/john30/ebusd-configuration/commit/05690d4698cffbdd64aae2ec17be677de5a5bbaa)

2025-02-16 07:08 UTC, closed without merging